# Generated by Django 4.2.2 on 2023-11-07 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Juridico',
            fields=[
                ('jur_id', models.AutoField(primary_key=True, serialize=False)),
                ('jur_nome_fantasia', models.CharField(max_length=100)),
                ('jur_telefone', models.IntegerField()),
                ('jur_foto', models.ImageField(blank=True, upload_to='')),
                ('jur_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Fisico',
            fields=[
                ('fis_id', models.AutoField(primary_key=True, serialize=False)),
                ('fis_foto', models.ImageField(blank=True, upload_to='')),
                ('fis_idade', models.IntegerField()),
                ('fis_sexo', models.CharField(max_length=15)),
                ('fis_nascimento', models.DateField()),
                ('fis_profissao', models.CharField(max_length=100)),
                ('fis_telefone', models.IntegerField()),
                ('fis_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
