# Generated by Django 4.2.2 on 2023-11-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_fisico',
            name='fis_foto',
            field=models.ImageField(blank=True, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='usuario_juridico',
            name='jur_foto',
            field=models.ImageField(blank=True, upload_to='imgs'),
        ),
    ]
