# Generated by Django 4.2.2 on 2023-11-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0002_alter_usuario_fisico_fis_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_fisico',
            name='fis_foto',
            field=models.ImageField(blank=True, upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='usuario_juridico',
            name='jur_foto',
            field=models.ImageField(blank=True, upload_to='imgs2/'),
        ),
    ]
