# Generated by Django 5.0 on 2023-12-21 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0003_alter_usuario_fisico_fis_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponto_Turistico',
            fields=[
                ('pon_id', models.AutoField(primary_key=True, serialize=False)),
                ('pon_nome', models.CharField(max_length=100)),
                ('pon_descricao', models.CharField(max_length=100)),
                ('pon_foto', models.ImageField(blank=True, upload_to='imgsPontos/')),
                ('pon_qrcode', models.ImageField(blank=True, upload_to='imgsPontos/')),
                ('pon_latitude', models.FloatField()),
                ('pon_longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco_Turistico',
            fields=[
                ('end_id', models.AutoField(primary_key=True, serialize=False)),
                ('end_cidade', models.CharField(max_length=100)),
                ('end_bairro', models.CharField(max_length=100)),
                ('end_rua', models.CharField(max_length=100)),
                ('end_numero', models.IntegerField()),
                ('end_pon_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_PP.ponto_turistico')),
            ],
        ),
    ]
