# Generated by Django 5.0 on 2024-01-23 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0004_ponto_turistico_endereco_turistico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_administrador',
            fields=[
                ('adm_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='ponto_turistico',
            name='pon_jur_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_PP.usuario_juridico'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Endereco_Usuario',
            fields=[
                ('endUser_id', models.AutoField(primary_key=True, serialize=False)),
                ('endUser_cidade', models.CharField(max_length=100)),
                ('endUser_estado', models.CharField(max_length=100)),
                ('endUser_pais', models.CharField(max_length=100)),
                ('endUser_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('per_id', models.AutoField(primary_key=True, serialize=False)),
                ('per_nivelPermissao', models.CharField(max_length=100)),
                ('per_jur_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_PP.usuario_juridico')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Governo',
            fields=[
                ('gov_id', models.AutoField(primary_key=True, serialize=False)),
                ('gov_telefone', models.IntegerField()),
                ('gov_foto', models.ImageField(blank=True, upload_to='imgs3/')),
                ('gov_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ponto_turistico',
            name='pon_gov_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_PP.usuario_governo'),
            preserve_default=False,
        ),
    ]
