# Generated by Django 5.0 on 2024-01-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0005_usuario_administrador_ponto_turistico_jur_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_turistico',
            name='pon_gov_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_PP.usuario_governo'),
        ),
        migrations.AlterField(
            model_name='ponto_turistico',
            name='pon_jur_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_PP.usuario_juridico'),
        ),
    ]
