# Generated by Django 5.0 on 2024-01-23 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0006_alter_ponto_turistico_pon_gov_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_turistico',
            name='pon_gov_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_PP.usuario_governo'),
        ),
    ]
