# Generated by Django 5.0 on 2024-01-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0008_usuario_administrador_adm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_administrador',
            name='adm_telefone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
