# Generated by Django 5.0 on 2024-01-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0009_usuario_administrador_adm_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto_turistico',
            name='pon_status',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
