# Generated by Django 5.0 on 2024-01-23 23:57

import app_PP.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0010_ponto_turistico_pon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponto_turistico',
            name='pon_foto',
            field=models.ImageField(blank=True, upload_to='imgsPontos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], 'apenas imagens são aceitas')]),
        ),
        migrations.AlterField(
            model_name='ponto_turistico',
            name='pon_qrcode',
            field=models.ImageField(blank=True, upload_to='imgsPontos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], 'apenas imagens são aceitas')]),
        ),
        migrations.AlterField(
            model_name='usuario_administrador',
            name='adm_telefone',
            field=models.FloatField(validators=[app_PP.validators.telefone]),
        ),
        migrations.AlterField(
            model_name='usuario_fisico',
            name='fis_foto',
            field=models.ImageField(blank=True, upload_to='imgs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], 'apenas imagens são aceitas')]),
        ),
        migrations.AlterField(
            model_name='usuario_fisico',
            name='fis_telefone',
            field=models.FloatField(validators=[app_PP.validators.telefone]),
        ),
        migrations.AlterField(
            model_name='usuario_governo',
            name='gov_foto',
            field=models.ImageField(blank=True, upload_to='imgs3/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], 'apenas imagens são aceitas')]),
        ),
        migrations.AlterField(
            model_name='usuario_governo',
            name='gov_telefone',
            field=models.FloatField(validators=[app_PP.validators.telefone]),
        ),
        migrations.AlterField(
            model_name='usuario_juridico',
            name='jur_foto',
            field=models.ImageField(blank=True, upload_to='imgs2/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'], 'apenas imagens são aceitas')]),
        ),
        migrations.AlterField(
            model_name='usuario_juridico',
            name='jur_telefone',
            field=models.FloatField(validators=[app_PP.validators.telefone]),
        ),
    ]
