# Generated by Django 5.0 on 2024-03-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0013_galeira_ponto_turistico'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristicoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('resumo', models.TextField()),
                ('url_imagem', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
