# Generated by Django 5.0 on 2024-03-24 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0014_pontoturisticoauto'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_avaliacoes',
            fields=[
                ('ava_id', models.AutoField(primary_key=True, serialize=False)),
                ('ava_avaliacao', models.FloatField()),
                ('ava_comentario', models.CharField(max_length=512)),
                ('ava_nota', models.IntegerField()),
                ('ava_fis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_PP.usuario_fisico')),
                ('ava_pon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_PP.ponto_turistico')),
            ],
        ),
        migrations.CreateModel(
            name='tb_favoritos',
            fields=[
                ('fav_id', models.AutoField(primary_key=True, serialize=False)),
                ('fav_fis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_PP.usuario_fisico')),
                ('fav_pon_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_PP.ponto_turistico')),
            ],
        ),
        migrations.CreateModel(
            name='tb_galeria_avaliacao',
            fields=[
                ('gal_id', models.AutoField(primary_key=True, serialize=False)),
                ('gal_descricao', models.CharField(max_length=45)),
                ('gal_foto', models.ImageField(blank=True, upload_to='imgs_pon/')),
                ('gal_ava_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_PP.tb_avaliacoes')),
            ],
        ),
    ]
