# Generated by Django 5.0 on 2024-05-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_PP', '0015_tb_avaliacoes_tb_favoritos_tb_galeria_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto_turistico',
            name='pon_foto',
        ),
    ]
